DROP DATABASE IF EXISTS BASKETBALL;
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BASKETBALL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BASKETBALL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BASKETBALL` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `BASKETBALL` ;

-- -----------------------------------------------------
-- Table `BASKETBALL`.`TEAM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`TEAM` (
  `ID` BIGINT NOT NULL,
  `FULL_NAME` VARCHAR(50) NULL DEFAULT NULL,
  `ABBREVIATION` CHAR(3) NOT NULL,
  `NICKNAME` VARCHAR(25) NULL DEFAULT NULL,
  `CITY` VARCHAR(50) NULL DEFAULT NULL,
  `STATE` VARCHAR(50) NULL DEFAULT NULL,
  `YEAR_FOUNDED` CHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FULL_NAME` (`FULL_NAME` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`DRAFT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`DRAFT` (
  `YEARDRAFT` INT NOT NULL,
  `NUMBERPICKOVERALL` SMALLINT NULL DEFAULT NULL,
  `NUMBERROUND` SMALLINT NULL DEFAULT NULL,
  `NUMBERROUNDPICK` SMALLINT NULL DEFAULT NULL,
  `NAMEORGANIZATIONFROM` VARCHAR(100) NULL DEFAULT NULL,
  `TYPEORGANIZATIONFROM` VARCHAR(50) NULL DEFAULT NULL,
  `IDPLAYER` BIGINT NOT NULL,
  `IDTEAM` BIGINT NOT NULL,
  `PLAYER_PROFILE_FLAG` SMALLINT NULL DEFAULT NULL,
  `LOCATIONORGANIZATIONFROM` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`IDPLAYER`, `YEARDRAFT`),
  INDEX `IDTEAM` (`IDTEAM` ASC) VISIBLE,
  CONSTRAINT `FK1_DRAFT_IDTEAM`
    FOREIGN KEY (`IDTEAM`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `BASKETBALL`.`GAME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`GAME` (
  `GAME_ID` BIGINT NOT NULL,
  `SEASON_ID` CHAR(5) NULL DEFAULT NULL,
  `TEAM_ID_HOME` BIGINT NOT NULL,
  `GAME_DATE` DATE NULL DEFAULT NULL,
  `WL_HOME` CHAR(1) NULL DEFAULT NULL,
  `MIN_HOME` INT NULL DEFAULT NULL,
  `FGM_HOME` INT NULL DEFAULT NULL,
  `FGA_HOME` INT NULL DEFAULT NULL,
  `FG_PCT_HOME` DOUBLE NULL DEFAULT NULL,
  `FG3M_HOME` INT NULL DEFAULT NULL,
  `FG3A_HOME` INT NULL DEFAULT NULL,
  `FG3_PCT_HOME` DOUBLE NULL DEFAULT NULL,
  `FTM_HOME` INT NULL DEFAULT NULL,
  `FTA_HOME` INT NULL DEFAULT NULL,
  `FT_PCT_HOME` DOUBLE NULL DEFAULT NULL,
  `OREB_HOME` INT NULL DEFAULT NULL,
  `DREB_HOME` INT NULL DEFAULT NULL,
  `REB_HOME` INT NULL DEFAULT NULL,
  `AST_HOME` INT NULL DEFAULT NULL,
  `STL_HOME` INT NULL DEFAULT NULL,
  `BLK_HOME` INT NULL DEFAULT NULL,
  `TOV_HOME` INT NULL DEFAULT NULL,
  `PF_HOME` INT NULL DEFAULT NULL,
  `PTS_HOME` INT NULL DEFAULT NULL,
  `PLUS_MINUS_HOME` INT NULL DEFAULT NULL,
  `VIDEO_AVAILABLE_HOME` INT NULL DEFAULT NULL,
  `TEAM_ID_OPP` BIGINT NOT NULL,
  `WL_OPP` CHAR(1) NULL DEFAULT NULL,
  `MIN_OPP` INT NULL DEFAULT NULL,
  `FGM_OPP` INT NULL DEFAULT NULL,
  `FGA_OPP` INT NULL DEFAULT NULL,
  `FG_PCT_OPP` DOUBLE NULL DEFAULT NULL,
  `FG3M_OPP` INT NULL DEFAULT NULL,
  `FG3A_OPP` INT NULL DEFAULT NULL,
  `FG3_PCT_OPP` DOUBLE NULL DEFAULT NULL,
  `FTM_OPP` INT NULL DEFAULT NULL,
  `FTA_OPP` INT NULL DEFAULT NULL,
  `FT_PCT_OPP` DOUBLE NULL DEFAULT NULL,
  `OREB_OPP` INT NULL DEFAULT NULL,
  `DREB_OPP` INT NULL DEFAULT NULL,
  `REB_OPP` INT NULL DEFAULT NULL,
  `AST_OPP` INT NULL DEFAULT NULL,
  `STL_OPP` INT NULL DEFAULT NULL,
  `BLK_OPP` INT NULL DEFAULT NULL,
  `TOV_OPP` INT NULL DEFAULT NULL,
  `PF_OPP` INT NULL DEFAULT NULL,
  `PTS_OPP` INT NULL DEFAULT NULL,
  `PLUS_MINUS_OPP` INT NULL DEFAULT NULL,
  `VIDEO_AVAILABLE_OPP` INT NULL DEFAULT NULL,
  `GAME_SEQUENCE` INT NULL DEFAULT NULL,
  `GAME_STATUS_ID` CHAR(1) NULL DEFAULT NULL,
  `GAME_STATUS_TEXT` VARCHAR(25) NULL DEFAULT NULL,
  `GAMECODE` VARCHAR(20) NULL DEFAULT NULL,
  `YEARS` CHAR(4) NULL DEFAULT NULL,
  `LIVE_PERIOD` INT NULL DEFAULT NULL,
  `LIVE_PC_TIME` VARCHAR(10) NULL DEFAULT NULL,
  `NATL_TV_BROADCASTER_ABBREVIATION` VARCHAR(10) NULL DEFAULT NULL,
  `LIVE_PERIOD_TIME_BCAST` VARCHAR(25) NULL DEFAULT NULL,
  `WH_STATUS` INT NULL DEFAULT NULL,
  `PTS_PAINT_HOME` INT NULL DEFAULT NULL,
  `PTS_2ND_CHANCE_HOME` INT NULL DEFAULT NULL,
  `PTS_FB_HOME` INT NULL DEFAULT NULL,
  `LARGEST_LEAD_HOME` INT NULL DEFAULT NULL,
  `LEAD_CHANGES_HOME` INT NULL DEFAULT NULL,
  `TIMES_TIED_HOME` INT NULL DEFAULT NULL,
  `TEAM_TURNOVERS_HOME` INT NULL DEFAULT NULL,
  `TOTAL_TURNOVERS_HOME` INT NULL DEFAULT NULL,
  `TEAM_REBOUNDS_HOME` INT NULL DEFAULT NULL,
  `PTS_OFF_TO_HOME` INT NULL DEFAULT NULL,
  `PTS_PAINT_OPP` INT NULL DEFAULT NULL,
  `PTS_2ND_CHANCE_OPP` INT NULL DEFAULT NULL,
  `PTS_FB_OPP` INT NULL DEFAULT NULL,
  `LARGEST_LEAD_OPP` INT NULL DEFAULT NULL,
  `LEAD_CHANGES_OPP` INT NULL DEFAULT NULL,
  `TIMES_TIED_OPP` INT NULL DEFAULT NULL,
  `TEAM_TURNOVERS_OPP` INT NULL DEFAULT NULL,
  `TOTAL_TURNOVERS_OPP` INT NULL DEFAULT NULL,
  `TEAM_REBOUNDS_OPP` INT NULL DEFAULT NULL,
  `PTS_OFF_TO_OPP` INT NULL DEFAULT NULL,
  `GAME_DAY` VARCHAR(15) NULL DEFAULT NULL,
  `GAME_MONTH` VARCHAR(15) NULL DEFAULT NULL,
  `ATTENDANCE` INT NULL DEFAULT NULL,
  `GAME_TIME` VARCHAR(10) NULL DEFAULT NULL,
  `PTS_QTR1_HOME` INT NULL DEFAULT NULL,
  `PTS_QTR2_HOME` INT NULL DEFAULT NULL,
  `PTS_QTR3_HOME` INT NULL DEFAULT NULL,
  `PTS_QTR4_HOME` INT NULL DEFAULT NULL,
  `PTS_OT1_HOME` INT NULL DEFAULT NULL,
  `PTS_OT2_HOME` INT NULL DEFAULT NULL,
  `PTS_OT3_HOME` INT NULL DEFAULT NULL,
  `PTS_OT4_HOME` INT NULL DEFAULT NULL,
  `PTS_OT5_HOME` INT NULL DEFAULT NULL,
  `PTS_QTR1_OPP` INT NULL DEFAULT NULL,
  `PTS_QTR2_OPP` INT NULL DEFAULT NULL,
  `PTS_QTR3_OPP` INT NULL DEFAULT NULL,
  `PTS_QTR4_OPP` INT NULL DEFAULT NULL,
  `PTS_OT1_OPP` INT NULL DEFAULT NULL,
  `PTS_OT2_OPP` INT NULL DEFAULT NULL,
  `PTS_OT3_OPP` INT NULL DEFAULT NULL,
  `PTS_OT4_OPP` INT NULL DEFAULT NULL,
  `PTS_OT5_OPP` INT NULL DEFAULT NULL,
  `LAST_GAME_ID` CHAR(10) NULL DEFAULT NULL,
  `HOME_TEAM_WINS` INT NULL DEFAULT NULL,
  `HOME_TEAM_LOSSES` INT NULL DEFAULT NULL,
  `SERIES_LEADER` VARCHAR(30) NULL DEFAULT NULL,
  `VIDEO_AVAILABLE_FLAG` INT NULL DEFAULT NULL,
  `PT_AVAILABLE` INT NULL DEFAULT NULL,
  `PT_XYZ_AVAILABLE` INT NULL DEFAULT NULL,
  `HUSTLE_STATUS` INT NULL DEFAULT NULL,
  `HISTORICAL_STATUS` INT NULL DEFAULT NULL,
  PRIMARY KEY (`GAME_ID`),
  INDEX `TEAM_ID_HOME` (`TEAM_ID_HOME` ASC) VISIBLE,
  INDEX `TEAM_ID_OPP` (`TEAM_ID_OPP` ASC) VISIBLE,
  CONSTRAINT `FK1_GAME_TEAM_ID_HOME`
    FOREIGN KEY (`TEAM_ID_HOME`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`),
  CONSTRAINT `FK2_GAME_TEAM_ID_OPP`
    FOREIGN KEY (`TEAM_ID_OPP`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`GAME_INACTIVE_PLAYERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`GAME_INACTIVE_PLAYERS` (
  `PLAYER_ID` BIGINT NOT NULL,
  `JERSEY_NUM` VARCHAR(5) NULL DEFAULT NULL,
  `TEAM_ID` BIGINT NOT NULL,
  `GAME_ID` CHAR(10) NOT NULL,
  PRIMARY KEY (`GAME_ID`, `PLAYER_ID`),
  INDEX `TEAM_ID` (`TEAM_ID` ASC) VISIBLE,
  CONSTRAINT `FK1_GAME_INACTIVE_PLAYERS_TEAM_ID`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`GAME_OFFICIAL_ATTRIBUTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`GAME_OFFICIAL_ATTRIBUTES` (
  `OFFICIAL_ID` BIGINT NOT NULL,
  `FIRST_NAME` VARCHAR(15) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(15) NULL DEFAULT NULL,
  `JERSEY_NUM` VARCHAR(5) NULL DEFAULT NULL,
  `GAME_ID` BIGINT NOT NULL,
  PRIMARY KEY (`GAME_ID`, `OFFICIAL_ID`),
  INDEX `GAME_ID` (`GAME_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`GAME_OFFICIALS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`GAME_OFFICIALS` (
  `GAME_GAME_ID` BIGINT NOT NULL,
  `GAME_OFFICIALS_OFFICIAL_ID` BIGINT NOT NULL,
  PRIMARY KEY (`GAME_GAME_ID`, `GAME_OFFICIALS_OFFICIAL_ID`),
  INDEX `fk_GAME_has_GAME_OFFICIALS_GAME_OFFICIALS1_idx` (`GAME_GAME_ID` ASC, `GAME_OFFICIALS_OFFICIAL_ID` ASC) VISIBLE,
  INDEX `fk_GAME_has_GAME_OFFICIALS_GAME1_idx` (`GAME_GAME_ID` ASC) VISIBLE,
  CONSTRAINT `FK1_GAME_OFFICIALS_GAME_GAME_ID`
    FOREIGN KEY (`GAME_GAME_ID`)
    REFERENCES `BASKETBALL`.`GAME` (`GAME_ID`),
  CONSTRAINT `FK2_GAME_GAME_ID_GAME_OFFICIALS_OFFICIAL_ID`
    FOREIGN KEY (`GAME_GAME_ID` , `GAME_OFFICIALS_OFFICIAL_ID`)
    REFERENCES `BASKETBALL`.`GAME_OFFICIAL_ATTRIBUTES` (`GAME_ID` , `OFFICIAL_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`PLAYER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`PLAYER` (
  `ID` BIGINT NOT NULL,
  `FULL_NAME` VARCHAR(30) NULL DEFAULT NULL,
  `FIRST_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(20) NULL DEFAULT NULL,
  `IS_ACTIVE` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`PLAYER_ATTRIBUTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`PLAYER_ATTRIBUTES` (
  `ID` BIGINT NOT NULL,
  `FULL_NAME` VARCHAR(30) NULL DEFAULT NULL,
  `PLAYER_SLUG` VARCHAR(25) NULL DEFAULT NULL,
  `BIRTHDATE` DATE NULL DEFAULT NULL,
  `SCHOOL` VARCHAR(35) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(25) NULL DEFAULT NULL,
  `LAST_AFFILIATION` VARCHAR(50) NULL DEFAULT NULL,
  `HEIGHT` INT NULL DEFAULT NULL,
  `WEIGHT` INT NULL DEFAULT NULL,
  `SEASON_EXP` INT NULL DEFAULT NULL,
  `JERSEY` VARCHAR(8) NULL DEFAULT NULL,
  `POSITION` VARCHAR(15) NULL DEFAULT NULL,
  `ROSTERSTATUS` VARCHAR(10) NULL DEFAULT NULL,
  `GAMES_PLAYED_CURRENT_SEASON_FLAG` CHAR(1) NULL DEFAULT NULL,
  `TEAM_ID` BIGINT NOT NULL,
  `PLAYERCODE` VARCHAR(40) NULL DEFAULT NULL,
  `FROM_YEAR` INT NULL DEFAULT NULL,
  `TO_YEAR` INT NULL DEFAULT NULL,
  `DLEAGUE_FLAG` CHAR(1) NULL DEFAULT NULL,
  `NBA_FLAG` CHAR(1) NULL DEFAULT NULL,
  `GAMES_PLAYED_FLAG` CHAR(1) NULL DEFAULT NULL,
  `PTS` DECIMAL(5,1) NULL DEFAULT NULL,
  `AST` DECIMAL(5,1) NULL DEFAULT NULL,
  `REB` DECIMAL(5,1) NULL DEFAULT NULL,
  `ALL_STAR_APPEARANCES` INT NULL DEFAULT NULL,
  `PIE` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TEAM_ID` (`TEAM_ID` ASC) VISIBLE,
  INDEX `FULL_NAME` (`FULL_NAME` ASC) VISIBLE,
  CONSTRAINT `FK1_PLAYER_ATTRIBUTES_TEAM_ID`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`),
  CONSTRAINT `FK2_PLAYER_ATTRIBUTES_PLAYER_ID`
    FOREIGN KEY (`ID`)
    REFERENCES `BASKETBALL`.`PLAYER` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`PLAYER_SALARY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`PLAYER_SALARY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SLUGSEASON` VARCHAR(8) NULL DEFAULT NULL,
  `NAMETEAM` VARCHAR(30) NULL DEFAULT NULL,
  `NAMEPLAYER` VARCHAR(30) NULL DEFAULT NULL,
  `STATUSPLAYER` VARCHAR(20) NULL DEFAULT NULL,
  `ISFINALSEASON` CHAR(1) NULL DEFAULT NULL,
  `ISWAIVED` CHAR(1) NULL DEFAULT NULL,
  `ISONROSTER` CHAR(1) NULL DEFAULT NULL,
  `ISNONGUARANTEED` CHAR(1) NULL DEFAULT NULL,
  `ISTEAMOPTION` CHAR(1) NULL DEFAULT NULL,
  `ISPLAYEROPTION` CHAR(1) NULL DEFAULT NULL,
  `TYPECONTRACTDETAIL` VARCHAR(20) NULL DEFAULT NULL,
  `SALARY` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NAMETEAM` (`NAMETEAM` ASC) VISIBLE,
  INDEX `NAMEPLAYER` (`NAMEPLAYER` ASC) VISIBLE,
  CONSTRAINT `FK1_PLAYER_SALARY_NAMETEAM`
    FOREIGN KEY (`NAMETEAM`)
    REFERENCES `BASKETBALL`.`TEAM` (`FULL_NAME`),
  CONSTRAINT `FK2_PLAYER_SALARY_NAMEPLAYER`
    FOREIGN KEY (`NAMEPLAYER`)
    REFERENCES `BASKETBALL`.`PLAYER_ATTRIBUTES` (`FULL_NAME`))
ENGINE = InnoDB
AUTO_INCREMENT = 3070
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`TEAM_ATTRIBUTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`TEAM_ATTRIBUTES` (
  `ID` BIGINT NOT NULL,
  `ABBREVIATION` CHAR(3) NOT NULL,
  `YEARFOUNDED` INT NULL DEFAULT NULL,
  `ARENA` VARCHAR(50) NULL DEFAULT NULL,
  `ARENACAPACITY` INT NULL DEFAULT NULL,
  `OWNERname` VARCHAR(50) NULL DEFAULT NULL,
  `GENERALMANAGER` VARCHAR(50) NULL DEFAULT NULL,
  `HEADCOACH` VARCHAR(50) NULL DEFAULT NULL,
  `DLEAGUEAFFILIATION` VARCHAR(50) NULL DEFAULT NULL,
  `FACEBOOK_WEBSITE_LINK` VARCHAR(50) NULL DEFAULT NULL,
  `INSTAGRAM_WEBSITE_LINK` VARCHAR(50) NULL DEFAULT NULL,
  `TWITTER_WEBSITE_LINK` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `ABBREVIATION`),
  INDEX `ID` (`ID` ASC) VISIBLE,
  CONSTRAINT `FK1_TEAM_ATTRIBUTES_ID`
    FOREIGN KEY (`ID`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`TEAM_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`TEAM_HISTORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEAM_ID` BIGINT NOT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `NICKNAME` VARCHAR(25) NULL DEFAULT NULL,
  `YEARFOUNDED` INT NOT NULL,
  `YEARACTIVETILL` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`, `CITY`),
  INDEX `team_history_ibfk_1` (`TEAM_ID` ASC) VISIBLE,
  CONSTRAINT `FK1_TEAM_HISTORY_TEAM_ID`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `BASKETBALL`.`TEAM` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 190
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`TEAM_SALARY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`TEAM_SALARY` (
  `NAMETEAM` VARCHAR(50) NULL DEFAULT NULL,
  `SLUGTEAM` CHAR(3) NOT NULL,
  `URLTEAMSALARYHOOPSHYPE` VARCHAR(100) NULL DEFAULT NULL,
  `X2020_21` FLOAT NULL DEFAULT NULL,
  `X2021_22` FLOAT NULL DEFAULT NULL,
  `X2022_23` FLOAT NULL DEFAULT NULL,
  `X2023_24` FLOAT NULL DEFAULT NULL,
  `X2024_25` FLOAT NULL DEFAULT NULL,
  `X2025_26` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`SLUGTEAM`),
  INDEX `NAMETEAM` (`NAMETEAM` ASC) VISIBLE,
  CONSTRAINT `FK1_TEAM_SALARY_NAMETEAM`
    FOREIGN KEY (`NAMETEAM`)
    REFERENCES `BASKETBALL`.`TEAM` (`FULL_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BASKETBALL`.`draft_Combine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASKETBALL`.`draft_Combine` (
  `YEARCOMBINE` INT NOT NULL,
  `IDPLAYER` BIGINT NOT NULL,
  `slugPosition` VARCHAR(15) NULL DEFAULT NULL,
  `heightWOShoesInches` FLOAT NULL DEFAULT NULL,
  `heightWOShoes` VARCHAR(15) NULL DEFAULT NULL,
  `weightLBS` FLOAT NULL DEFAULT NULL,
  `wingspanInches` FLOAT NULL DEFAULT NULL,
  `wingspan` VARCHAR(15) NULL DEFAULT NULL,
  `reachStandingInches` FLOAT NULL DEFAULT NULL,
  `reachStandingO` VARCHAR(15) NULL DEFAULT NULL,
  `verticalLeapStandingInches` FLOAT NULL DEFAULT NULL,
  `verticalLeapMaxInches` FLOAT NULL DEFAULT NULL,
  `timeLaneAgility` FLOAT NULL DEFAULT NULL,
  `timeThreeQuarterCourtSprint` FLOAT NULL DEFAULT NULL,
  `repsBenchPress135` FLOAT NULL DEFAULT NULL,
  `pctBodyFat` FLOAT NULL DEFAULT NULL,
  `heightWShoesInches` FLOAT NULL DEFAULT NULL,
  `heightWShoes` VARCHAR(15) NULL DEFAULT NULL,
  `lengthHandInches` FLOAT NULL DEFAULT NULL,
  `widthHandInches` FLOAT NULL DEFAULT NULL,
  `timeModifiedLaneAgility` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeft` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15BreakLeft` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15TopKey` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15BreakRight` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15CornerRight` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15CornerLeftCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15BreakLeftCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15TopKeyCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15BreakRightCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15CornerRightCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15CornerLeftNBA` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15BreakLeftNBA` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15TopKeyNBA` VARCHAR(10) NULL DEFAULT NULL,
  `setSpotBreakRightNBA` VARCHAR(10) NULL DEFAULT NULL,
  `setSpotCornerRightNBA` VARCHAR(10) NULL DEFAULT NULL,
  `setSpot15CornerLeftMade` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftPct` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftMade` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftPct` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyMade` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyPct` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightMade` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightPct` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightMade` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightPct` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftCollegeMade` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftCollegePct` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftCollegeMade` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftCollegePct` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyCollegeMade` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyCollegePct` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightCollegeMade` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakRightCollegePct` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightCollegeMade` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerRightCollegePct` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftNBAMade` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftNBAAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15CornerLeftNBAPct` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftNBAMade` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftNBAAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15BreakLeftNBAPct` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyNBAMade` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyNBAAttempted` FLOAT NULL DEFAULT NULL,
  `setSpot15TopKeyNBAPct` FLOAT NULL DEFAULT NULL,
  `setSpotBreakRightNBAMade` FLOAT NULL DEFAULT NULL,
  `setSpotBreakRightNBAAttempted` FLOAT NULL DEFAULT NULL,
  `setSpotBreakRightNBAPct` FLOAT NULL DEFAULT NULL,
  `setSpotCornerRightNBAMade` FLOAT NULL DEFAULT NULL,
  `setSpotCornerRightNBAAttempted` FLOAT NULL DEFAULT NULL,
  `setSpotCornerRightNBAPct` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakLeft` VARCHAR(10) NULL DEFAULT NULL,
  `setSpotOffDrib15TopKey` VARCHAR(10) NULL DEFAULT NULL,
  `setOffDrib15BreakRight` VARCHAR(10) NULL DEFAULT NULL,
  `setOnMove15` VARCHAR(10) NULL DEFAULT NULL,
  `setOnMoveCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setOffDrib15BreakLeftMade` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakLeftAttempted` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakLeftPct` FLOAT NULL DEFAULT NULL,
  `setSpotOffDrib15TopKeyMade` FLOAT NULL DEFAULT NULL,
  `setSpotOffDrib15TopKeyAttempted` FLOAT NULL DEFAULT NULL,
  `setSpotOffDrib15TopKeyPct` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakRightMade` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakRightAttempted` FLOAT NULL DEFAULT NULL,
  `setOffDrib15BreakRightPct` FLOAT NULL DEFAULT NULL,
  `setOnMove15Made` FLOAT NULL DEFAULT NULL,
  `setOnMove15Attempted` FLOAT NULL DEFAULT NULL,
  `setOnMove15Pct` FLOAT NULL DEFAULT NULL,
  `setOnMoveCollegeMade` FLOAT NULL DEFAULT NULL,
  `setOnMoveCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setOnMoveCollegePct` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakLeftCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setOffDribTopKeyCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setOffDribBreakRightCollege` VARCHAR(10) NULL DEFAULT NULL,
  `setOffDribBreakLeftCollegeMade` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakLeftCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakLeftCollegePct` FLOAT NULL DEFAULT NULL,
  `setOffDribTopKeyCollegeMade` FLOAT NULL DEFAULT NULL,
  `setOffDribTopKeyCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setOffDribTopKeyCollegePct` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakRightCollegeMade` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakRightCollegeAttempted` FLOAT NULL DEFAULT NULL,
  `setOffDribBreakRightCollegePct` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IDPLAYER`, `YEARCOMBINE`),
  INDEX `IDPLAYER` (`IDPLAYER` ASC) VISIBLE,
  CONSTRAINT `FK1_draft_Combine`
    FOREIGN KEY (`IDPLAYER`)
    REFERENCES `BASKETBALL`.`PLAYER` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
