insert into basketball.Team
(
ID
,FULL_NAME
,ABBREVIATION
,NICKNAME
,CITY
,STATE
,YEAR_FOUNDED
)
select
id
,full_name
,abbreviation
,nickname
,city
,state
,year_founded
from basketball_test.Team;

insert into basketball.Draft
(
yearDraft
,numberPickOverall
,numberRound
,numberRoundPick
,nameOrganizationFrom
,typeOrganizationFrom
,idPlayer
,idTeam
,PLAYER_PROFILE_FLAG
,locationOrganizationFrom
)
select 
yearDraft
,numberPickOverall
,numberRound
,numberRoundPick
,nameOrganizationFrom
,typeOrganizationFrom
,idPlayer
,idTeam
,PLAYER_PROFILE_FLAG
,locationOrganizationFrom
from (
select
yearDraft
,numberPickOverall
,numberRound
,numberRoundPick
,namePlayer
,slugTeam
,nameOrganizationFrom
,typeOrganizationFrom
,idPlayer
,idTeam
,nameTeam
,cityTeam
,teamName
,PLAYER_PROFILE_FLAG
,locationOrganizationFrom
,row_number()over(partition by IDPLAYER,yearDraft order by IDPLAYER,yearDraft) as ro1
from basketball_test.Draft
where idTeam in (select id from basketball.Team)
 ) T
 where ro1 = 1;

insert into basketball.Player
(
ID
,FULL_NAME
,FIRST_NAME
,LAST_NAME
,IS_ACTIVE
)
select
ID
,FULL_NAME
,FIRST_NAME
,LAST_NAME
,IS_ACTIVE
from basketball_test.Player;

insert into basketball.DRAFT_COMBINE
(
YEARCOMBINE
,IDPLAYER
,SLUGPOSITION
,HEIGHTWOSHOESINCHES
,HEIGHTWOSHOES
,WEIGHTLBS
,WINGSPANINCHES
,WINGSPAN
,REACHSTANDINGINCHES
,REACHSTANDINGO
,VERTICALLEAPSTANDINGINCHES
,VERTICALLEAPMAXINCHES
,TIMELANEAGILITY
,TIMETHREEQUARTERCOURTSPRINT
,REPSBENCHPRESS135
,PCTBODYFAT
,HEIGHTWSHOESINCHES
,HEIGHTWSHOES
,LENGTHHANDINCHES
,WIDTHHANDINCHES
,TIMEMODIFIEDLANEAGILITY
,SETSPOT15CORNERLEFT
,SETSPOT15BREAKLEFT
,SETSPOT15TOPKEY
,SETSPOT15BREAKRIGHT
,SETSPOT15CORNERRIGHT
,SETSPOT15CORNERLEFTCOLLEGE
,SETSPOT15BREAKLEFTCOLLEGE
,SETSPOT15TOPKEYCOLLEGE
,SETSPOT15BREAKRIGHTCOLLEGE
,SETSPOT15CORNERRIGHTCOLLEGE
,SETSPOT15CORNERLEFTNBA
,SETSPOT15BREAKLEFTNBA
,SETSPOT15TOPKEYNBA
,SETSPOTBREAKRIGHTNBA
,SETSPOTCORNERRIGHTNBA
,SETSPOT15CORNERLEFTMADE
,SETSPOT15CORNERLEFTATTEMPTED
,SETSPOT15CORNERLEFTPCT
,SETSPOT15BREAKLEFTMADE
,SETSPOT15BREAKLEFTATTEMPTED
,SETSPOT15BREAKLEFTPCT
,SETSPOT15TOPKEYMADE
,SETSPOT15TOPKEYATTEMPTED
,SETSPOT15TOPKEYPCT
,SETSPOT15BREAKRIGHTMADE
,SETSPOT15BREAKRIGHTATTEMPTED
,SETSPOT15BREAKRIGHTPCT
,SETSPOT15CORNERRIGHTMADE
,SETSPOT15CORNERRIGHTATTEMPTED
,SETSPOT15CORNERRIGHTPCT
,SETSPOT15CORNERLEFTCOLLEGEMADE
,SETSPOT15CORNERLEFTCOLLEGEATTEMPTED
,SETSPOT15CORNERLEFTCOLLEGEPCT
,SETSPOT15BREAKLEFTCOLLEGEMADE
,SETSPOT15BREAKLEFTCOLLEGEATTEMPTED
,SETSPOT15BREAKLEFTCOLLEGEPCT
,SETSPOT15TOPKEYCOLLEGEMADE
,SETSPOT15TOPKEYCOLLEGEATTEMPTED
,SETSPOT15TOPKEYCOLLEGEPCT
,SETSPOT15BREAKRIGHTCOLLEGEMADE
,SETSPOT15BREAKRIGHTCOLLEGEATTEMPTED
,SETSPOT15BREAKRIGHTCOLLEGEPCT
,SETSPOT15CORNERRIGHTCOLLEGEMADE
,SETSPOT15CORNERRIGHTCOLLEGEATTEMPTED
,SETSPOT15CORNERRIGHTCOLLEGEPCT
,SETSPOT15CORNERLEFTNBAMADE
,SETSPOT15CORNERLEFTNBAATTEMPTED
,SETSPOT15CORNERLEFTNBAPCT
,SETSPOT15BREAKLEFTNBAMADE
,SETSPOT15BREAKLEFTNBAATTEMPTED
,SETSPOT15BREAKLEFTNBAPCT
,SETSPOT15TOPKEYNBAMADE
,SETSPOT15TOPKEYNBAATTEMPTED
,SETSPOT15TOPKEYNBAPCT
,SETSPOTBREAKRIGHTNBAMADE
,SETSPOTBREAKRIGHTNBAATTEMPTED
,SETSPOTBREAKRIGHTNBAPCT
,SETSPOTCORNERRIGHTNBAMADE
,SETSPOTCORNERRIGHTNBAATTEMPTED
,SETSPOTCORNERRIGHTNBAPCT
,SETOFFDRIB15BREAKLEFT
,SETSPOTOFFDRIB15TOPKEY
,SETOFFDRIB15BREAKRIGHT
,SETONMOVE15
,SETONMOVECOLLEGE
,SETOFFDRIB15BREAKLEFTMADE
,SETOFFDRIB15BREAKLEFTATTEMPTED
,SETOFFDRIB15BREAKLEFTPCT
,SETSPOTOFFDRIB15TOPKEYMADE
,SETSPOTOFFDRIB15TOPKEYATTEMPTED
,SETSPOTOFFDRIB15TOPKEYPCT
,SETOFFDRIB15BREAKRIGHTMADE
,SETOFFDRIB15BREAKRIGHTATTEMPTED
,SETOFFDRIB15BREAKRIGHTPCT
,SETONMOVE15MADE
,SETONMOVE15ATTEMPTED
,SETONMOVE15PCT
,SETONMOVECOLLEGEMADE
,SETONMOVECOLLEGEATTEMPTED
,SETONMOVECOLLEGEPCT
,SETOFFDRIBBREAKLEFTCOLLEGE
,SETOFFDRIBTOPKEYCOLLEGE
,SETOFFDRIBBREAKRIGHTCOLLEGE
,SETOFFDRIBBREAKLEFTCOLLEGEMADE
,SETOFFDRIBBREAKLEFTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKLEFTCOLLEGEPCT
,SETOFFDRIBTOPKEYCOLLEGEMADE
,SETOFFDRIBTOPKEYCOLLEGEATTEMPTED
,SETOFFDRIBTOPKEYCOLLEGEPCT
,SETOFFDRIBBREAKRIGHTCOLLEGEMADE
,SETOFFDRIBBREAKRIGHTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKRIGHTCOLLEGEPCT
)
select 
YEARCOMBINE
,IDPLAYER
,SLUGPOSITION
,HEIGHTWOSHOESINCHES
,HEIGHTWOSHOES
,WEIGHTLBS
,WINGSPANINCHES
,WINGSPAN
,REACHSTANDINGINCHES
,REACHSTANDINGO
,VERTICALLEAPSTANDINGINCHES
,VERTICALLEAPMAXINCHES
,TIMELANEAGILITY
,TIMETHREEQUARTERCOURTSPRINT
,REPSBENCHPRESS135
,PCTBODYFAT
,HEIGHTWSHOESINCHES
,HEIGHTWSHOES
,LENGTHHANDINCHES
,WIDTHHANDINCHES
,TIMEMODIFIEDLANEAGILITY
,SETSPOT15CORNERLEFT
,SETSPOT15BREAKLEFT
,SETSPOT15TOPKEY
,SETSPOT15BREAKRIGHT
,SETSPOT15CORNERRIGHT
,SETSPOT15CORNERLEFTCOLLEGE
,SETSPOT15BREAKLEFTCOLLEGE
,SETSPOT15TOPKEYCOLLEGE
,SETSPOT15BREAKRIGHTCOLLEGE
,SETSPOT15CORNERRIGHTCOLLEGE
,SETSPOT15CORNERLEFTNBA
,SETSPOT15BREAKLEFTNBA
,SETSPOT15TOPKEYNBA
,SETSPOTBREAKRIGHTNBA
,SETSPOTCORNERRIGHTNBA
,SETSPOT15CORNERLEFTMADE
,SETSPOT15CORNERLEFTATTEMPTED
,SETSPOT15CORNERLEFTPCT
,SETSPOT15BREAKLEFTMADE
,SETSPOT15BREAKLEFTATTEMPTED
,SETSPOT15BREAKLEFTPCT
,SETSPOT15TOPKEYMADE
,SETSPOT15TOPKEYATTEMPTED
,SETSPOT15TOPKEYPCT
,SETSPOT15BREAKRIGHTMADE
,SETSPOT15BREAKRIGHTATTEMPTED
,SETSPOT15BREAKRIGHTPCT
,SETSPOT15CORNERRIGHTMADE
,SETSPOT15CORNERRIGHTATTEMPTED
,SETSPOT15CORNERRIGHTPCT
,SETSPOT15CORNERLEFTCOLLEGEMADE
,SETSPOT15CORNERLEFTCOLLEGEATTEMPTED
,SETSPOT15CORNERLEFTCOLLEGEPCT
,SETSPOT15BREAKLEFTCOLLEGEMADE
,SETSPOT15BREAKLEFTCOLLEGEATTEMPTED
,SETSPOT15BREAKLEFTCOLLEGEPCT
,SETSPOT15TOPKEYCOLLEGEMADE
,SETSPOT15TOPKEYCOLLEGEATTEMPTED
,SETSPOT15TOPKEYCOLLEGEPCT
,SETSPOT15BREAKRIGHTCOLLEGEMADE
,SETSPOT15BREAKRIGHTCOLLEGEATTEMPTED
,SETSPOT15BREAKRIGHTCOLLEGEPCT
,SETSPOT15CORNERRIGHTCOLLEGEMADE
,SETSPOT15CORNERRIGHTCOLLEGEATTEMPTED
,SETSPOT15CORNERRIGHTCOLLEGEPCT
,SETSPOT15CORNERLEFTNBAMADE
,SETSPOT15CORNERLEFTNBAATTEMPTED
,SETSPOT15CORNERLEFTNBAPCT
,SETSPOT15BREAKLEFTNBAMADE
,SETSPOT15BREAKLEFTNBAATTEMPTED
,SETSPOT15BREAKLEFTNBAPCT
,SETSPOT15TOPKEYNBAMADE
,SETSPOT15TOPKEYNBAATTEMPTED
,SETSPOT15TOPKEYNBAPCT
,SETSPOTBREAKRIGHTNBAMADE
,SETSPOTBREAKRIGHTNBAATTEMPTED
,SETSPOTBREAKRIGHTNBAPCT
,SETSPOTCORNERRIGHTNBAMADE
,SETSPOTCORNERRIGHTNBAATTEMPTED
,SETSPOTCORNERRIGHTNBAPCT
,SETOFFDRIB15BREAKLEFT
,SETSPOTOFFDRIB15TOPKEY
,SETOFFDRIB15BREAKRIGHT
,SETONMOVE15
,SETONMOVECOLLEGE
,SETOFFDRIB15BREAKLEFTMADE
,SETOFFDRIB15BREAKLEFTATTEMPTED
,SETOFFDRIB15BREAKLEFTPCT
,SETSPOTOFFDRIB15TOPKEYMADE
,SETSPOTOFFDRIB15TOPKEYATTEMPTED
,SETSPOTOFFDRIB15TOPKEYPCT
,SETOFFDRIB15BREAKRIGHTMADE
,SETOFFDRIB15BREAKRIGHTATTEMPTED
,SETOFFDRIB15BREAKRIGHTPCT
,SETONMOVE15MADE
,SETONMOVE15ATTEMPTED
,SETONMOVE15PCT
,SETONMOVECOLLEGEMADE
,SETONMOVECOLLEGEATTEMPTED
,SETONMOVECOLLEGEPCT
,SETOFFDRIBBREAKLEFTCOLLEGE
,SETOFFDRIBTOPKEYCOLLEGE
,SETOFFDRIBBREAKRIGHTCOLLEGE
,SETOFFDRIBBREAKLEFTCOLLEGEMADE
,SETOFFDRIBBREAKLEFTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKLEFTCOLLEGEPCT
,SETOFFDRIBTOPKEYCOLLEGEMADE
,SETOFFDRIBTOPKEYCOLLEGEATTEMPTED
,SETOFFDRIBTOPKEYCOLLEGEPCT
,SETOFFDRIBBREAKRIGHTCOLLEGEMADE
,SETOFFDRIBBREAKRIGHTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKRIGHTCOLLEGEPCT
from (
select
YEARCOMBINE
,IDPLAYER
,SLUGPOSITION
,HEIGHTWOSHOESINCHES
,HEIGHTWOSHOES
,WEIGHTLBS
,WINGSPANINCHES
,WINGSPAN
,REACHSTANDINGINCHES
,REACHSTANDINGO
,VERTICALLEAPSTANDINGINCHES
,VERTICALLEAPMAXINCHES
,TIMELANEAGILITY
,TIMETHREEQUARTERCOURTSPRINT
,REPSBENCHPRESS135
,PCTBODYFAT
,HEIGHTWSHOESINCHES
,HEIGHTWSHOES
,LENGTHHANDINCHES
,WIDTHHANDINCHES
,TIMEMODIFIEDLANEAGILITY
,SETSPOT15CORNERLEFT
,SETSPOT15BREAKLEFT
,SETSPOT15TOPKEY
,SETSPOT15BREAKRIGHT
,SETSPOT15CORNERRIGHT
,SETSPOT15CORNERLEFTCOLLEGE
,SETSPOT15BREAKLEFTCOLLEGE
,SETSPOT15TOPKEYCOLLEGE
,SETSPOT15BREAKRIGHTCOLLEGE
,SETSPOT15CORNERRIGHTCOLLEGE
,SETSPOT15CORNERLEFTNBA
,SETSPOT15BREAKLEFTNBA
,SETSPOT15TOPKEYNBA
,SETSPOTBREAKRIGHTNBA
,SETSPOTCORNERRIGHTNBA
,SETSPOT15CORNERLEFTMADE
,SETSPOT15CORNERLEFTATTEMPTED
,SETSPOT15CORNERLEFTPCT
,SETSPOT15BREAKLEFTMADE
,SETSPOT15BREAKLEFTATTEMPTED
,SETSPOT15BREAKLEFTPCT
,SETSPOT15TOPKEYMADE
,SETSPOT15TOPKEYATTEMPTED
,SETSPOT15TOPKEYPCT
,SETSPOT15BREAKRIGHTMADE
,SETSPOT15BREAKRIGHTATTEMPTED
,SETSPOT15BREAKRIGHTPCT
,SETSPOT15CORNERRIGHTMADE
,SETSPOT15CORNERRIGHTATTEMPTED
,SETSPOT15CORNERRIGHTPCT
,SETSPOT15CORNERLEFTCOLLEGEMADE
,SETSPOT15CORNERLEFTCOLLEGEATTEMPTED
,SETSPOT15CORNERLEFTCOLLEGEPCT
,SETSPOT15BREAKLEFTCOLLEGEMADE
,SETSPOT15BREAKLEFTCOLLEGEATTEMPTED
,SETSPOT15BREAKLEFTCOLLEGEPCT
,SETSPOT15TOPKEYCOLLEGEMADE
,SETSPOT15TOPKEYCOLLEGEATTEMPTED
,SETSPOT15TOPKEYCOLLEGEPCT
,SETSPOT15BREAKRIGHTCOLLEGEMADE
,SETSPOT15BREAKRIGHTCOLLEGEATTEMPTED
,SETSPOT15BREAKRIGHTCOLLEGEPCT
,SETSPOT15CORNERRIGHTCOLLEGEMADE
,SETSPOT15CORNERRIGHTCOLLEGEATTEMPTED
,SETSPOT15CORNERRIGHTCOLLEGEPCT
,SETSPOT15CORNERLEFTNBAMADE
,SETSPOT15CORNERLEFTNBAATTEMPTED
,SETSPOT15CORNERLEFTNBAPCT
,SETSPOT15BREAKLEFTNBAMADE
,SETSPOT15BREAKLEFTNBAATTEMPTED
,SETSPOT15BREAKLEFTNBAPCT
,SETSPOT15TOPKEYNBAMADE
,SETSPOT15TOPKEYNBAATTEMPTED
,SETSPOT15TOPKEYNBAPCT
,SETSPOTBREAKRIGHTNBAMADE
,SETSPOTBREAKRIGHTNBAATTEMPTED
,SETSPOTBREAKRIGHTNBAPCT
,SETSPOTCORNERRIGHTNBAMADE
,SETSPOTCORNERRIGHTNBAATTEMPTED
,SETSPOTCORNERRIGHTNBAPCT
,SETOFFDRIB15BREAKLEFT
,SETSPOTOFFDRIB15TOPKEY
,SETOFFDRIB15BREAKRIGHT
,SETONMOVE15
,SETONMOVECOLLEGE
,SETOFFDRIB15BREAKLEFTMADE
,SETOFFDRIB15BREAKLEFTATTEMPTED
,SETOFFDRIB15BREAKLEFTPCT
,SETSPOTOFFDRIB15TOPKEYMADE
,SETSPOTOFFDRIB15TOPKEYATTEMPTED
,SETSPOTOFFDRIB15TOPKEYPCT
,SETOFFDRIB15BREAKRIGHTMADE
,SETOFFDRIB15BREAKRIGHTATTEMPTED
,SETOFFDRIB15BREAKRIGHTPCT
,SETONMOVE15MADE
,SETONMOVE15ATTEMPTED
,SETONMOVE15PCT
,SETONMOVECOLLEGEMADE
,SETONMOVECOLLEGEATTEMPTED
,SETONMOVECOLLEGEPCT
,SETOFFDRIBBREAKLEFTCOLLEGE
,SETOFFDRIBTOPKEYCOLLEGE
,SETOFFDRIBBREAKRIGHTCOLLEGE
,SETOFFDRIBBREAKLEFTCOLLEGEMADE
,SETOFFDRIBBREAKLEFTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKLEFTCOLLEGEPCT
,SETOFFDRIBTOPKEYCOLLEGEMADE
,SETOFFDRIBTOPKEYCOLLEGEATTEMPTED
,SETOFFDRIBTOPKEYCOLLEGEPCT
,SETOFFDRIBBREAKRIGHTCOLLEGEMADE
,SETOFFDRIBBREAKRIGHTCOLLEGEATTEMPTED
,SETOFFDRIBBREAKRIGHTCOLLEGEPCT
,row_number()over(partition by IDPLAYER,YEARCOMBINE order by IDPLAYER,YEARCOMBINE) as ro1
from basketball_test.DRAFT_COMBINE
where IDPLAYER in (select id from basketball.player)
 ) T
 where ro1 = 1;

-- FIX SEASON, REMOVE TEAM_NAME, TEAM_ABBREVIATION, LAST_GAME_HOME_TEAM_CITY, NAME, ABBREVIATION
INSERT INTO BASKETBALL.GAME
(
AST_HOME,
AST_OPP,
ATTENDANCE,
BLK_HOME,
BLK_OPP,
DREB_HOME,
DREB_OPP,
FG_PCT_HOME,
FG_PCT_OPP,
FG3_PCT_HOME,
FG3_PCT_OPP,
FG3A_HOME,
FG3A_OPP,
FG3M_HOME,
FG3M_OPP,
FGA_HOME,
FGA_OPP,
FGM_HOME,
FGM_OPP,
FT_PCT_HOME,
FT_PCT_OPP,
FTA_HOME,
FTA_OPP,
FTM_HOME,
FTM_OPP,
GAME_DATE,
GAME_DAY,
GAME_ID,
GAME_MONTH,
GAME_SEQUENCE,
GAME_STATUS_ID,
GAME_STATUS_TEXT,
GAME_TIME,
GAMECODE,
HISTORICAL_STATUS,
HOME_TEAM_LOSSES,
HOME_TEAM_WINS,
HUSTLE_STATUS,
LARGEST_LEAD_HOME,
LARGEST_LEAD_OPP,
LAST_GAME_ID,
LEAD_CHANGES_HOME,
LEAD_CHANGES_OPP,
LIVE_PC_TIME,
LIVE_PERIOD,
LIVE_PERIOD_TIME_BCAST,
MIN_HOME,
MIN_OPP,
NATL_TV_BROADCASTER_ABBREVIATION,
OREB_HOME,
OREB_OPP,
PF_HOME,
PF_OPP,
PLUS_MINUS_HOME,
PLUS_MINUS_OPP,
PT_AVAILABLE,
PT_XYZ_AVAILABLE,
PTS_2ND_CHANCE_HOME,
PTS_2ND_CHANCE_OPP,
PTS_FB_HOME,
PTS_FB_OPP,
PTS_HOME,
PTS_OFF_TO_HOME,
PTS_OFF_TO_OPP,
PTS_OPP,
PTS_OT1_HOME,
PTS_OT1_OPP,
PTS_OT2_HOME,
PTS_OT2_OPP,
PTS_OT3_HOME,
PTS_OT3_OPP,
PTS_OT4_HOME,
PTS_OT4_OPP,
PTS_OT5_HOME,
PTS_OT5_OPP,
PTS_PAINT_HOME,
PTS_PAINT_OPP,
PTS_QTR1_HOME,
PTS_QTR1_OPP,
PTS_QTR2_HOME,
PTS_QTR2_OPP,
PTS_QTR3_HOME,
PTS_QTR3_OPP,
PTS_QTR4_HOME,
PTS_QTR4_OPP,
REB_HOME,
REB_OPP,
SEASON_ID,
SERIES_LEADER,
STL_HOME,
STL_OPP,
TEAM_ID_HOME,
TEAM_ID_OPP,
TEAM_REBOUNDS_HOME,
TEAM_REBOUNDS_OPP,
TEAM_TURNOVERS_HOME,
TEAM_TURNOVERS_OPP,
TIMES_TIED_HOME,
TIMES_TIED_OPP,
TOTAL_TURNOVERS_HOME,
TOTAL_TURNOVERS_OPP,
TOV_HOME,
TOV_OPP,
VIDEO_AVAILABLE_FLAG,
VIDEO_AVAILABLE_HOME,
VIDEO_AVAILABLE_OPP,
WH_STATUS,
WL_HOME,
WL_OPP,
YEARS
)
SELECT
AST_HOME,
AST_AWAY AS AST_OPP,
ATTENDANCE,
BLK_HOME,
BLK_AWAY AS BLK_OPP,
DREB_HOME,
DREB_AWAY AS DREB_OPP,
FG_PCT_HOME,
FG_PCT_AWAY AS FG_PCT_OPP,
FG3_PCT_HOME,
FG3_PCT_AWAY AS FG3_PCT_OPP,
FG3A_HOME,
FG3A_AWAY AS FG3A_OPP,
FG3M_HOME,
FG3M_AWAY AS FG3M_OPP,
FGA_HOME,
FGA_AWAY AS FGA_OPP,
FGM_HOME,
FGM_AWAY AS FGM_OPP,
FT_PCT_HOME,
FT_PCT_AWAY AS FT_PCT_OPP,
FTA_HOME,
FTA_AWAY AS FTA_OPP,
FTM_HOME,
FTM_AWAY AS FTM_OPP,
GAME_DATE,
SUBSTRING_INDEX(GAME_DATE_DAY, ',', 1) AS GAME_DAY,
GAME_ID,
EXTRACT(MONTH FROM GAME_DATE) AS GAME_MONTH,
GAME_SEQUENCE,
GAME_STATUS_ID,
GAME_STATUS_TEXT,
GAME_TIME,
GAMECODE,
HISTORICAL_STATUS,
HOME_TEAM_LOSSES,
HOME_TEAM_WINS,
HUSTLE_STATUS,
LARGEST_LEAD_HOME,
LARGEST_LEAD_AWAY LARGEST_LEAD_OPP,
LAST_GAME_ID,
LEAD_CHANGES_HOME,
LEAD_CHANGES_AWAY,
LIVE_PC_TIME,
LIVE_PERIOD,
LIVE_PERIOD_TIME_BCAST,
MIN_HOME,
MIN_AWAY MIN_OPP,
NATL_TV_BROADCASTER_ABBREVIATION,
OREB_HOME,
OREB_AWAY OREB_OPP,
PF_HOME,
PF_AWAY PF_OPP,
PLUS_MINUS_HOME,
PLUS_MINUS_AWAY PLUS_MINUS_OPP,
PT_AVAILABLE,
PT_XYZ_AVAILABLE,
PTS_2ND_CHANCE_HOME,
PTS_2ND_CHANCE_AWAY PTS_2ND_CHANCE_OPP,
PTS_FB_HOME,
PTS_FB_AWAY PTS_FB_OPP,
PTS_HOME,
PTS_OFF_TO_HOME,
PTS_OFF_TO_AWAY PTS_OFF_TO_OPP,
PTS_AWAY PTS_OPP,
PTS_OT1_HOME,
PTS_OT1_AWAY PTS_OT1_OPP,
PTS_OT2_HOME,
PTS_OT2_AWAY PTS_OT2_OPP,
PTS_OT3_HOME,
PTS_OT3_AWAY PTS_OT3_OPP,
PTS_OT4_HOME,
PTS_OT4_AWAY PTS_OT4_OPP,
PTS_OT5_HOME,
PTS_OT5_AWAY PTS_OT5_OPP,
PTS_PAINT_HOME,
PTS_PAINT_AWAY PTS_PAINT_OPP,
PTS_QTR1_HOME,
PTS_QTR1_AWAY PTS_QTR1_OPP,
PTS_QTR2_HOME,
PTS_QTR2_AWAY PTS_QTR2_OPP,
PTS_QTR3_HOME,
PTS_QTR3_AWAY PTS_QTR3_OPP,
PTS_QTR4_HOME,
PTS_QTR4_AWAY PTS_QTR4_OPP,
REB_HOME,
REB_AWAY REB_OPP,
(SEASON_ID-20000) AS SEASON_ID,
SERIES_LEADER,
STL_HOME,
STL_AWAY STL_OPP,
TEAM_ID_HOME,
TEAM_ID_AWAY TEAM_ID_OPP,
TEAM_REBOUNDS_HOME,
TEAM_REBOUNDS_AWAY TEAM_REBOUNDS_OPP,
TEAM_TURNOVERS_HOME,
TEAM_TURNOVERS_AWAY TEAM_TURNOVERS_OPP,
TIMES_TIED_HOME,
TIMES_TIED_AWAY TIMES_TIED_OPP,
TOTAL_TURNOVERS_HOME,
TOTAL_TURNOVERS_AWAY TOTAL_TURNOVERS_OPP,
TOV_HOME,
TOV_AWAY TOV_OPP,
VIDEO_AVAILABLE_FLAG,
VIDEO_AVAILABLE_HOME,
VIDEO_AVAILABLE_AWAY VIDEO_AVAILABLE_OPP,
WH_STATUS,
WL_HOME,
WL_AWAY WL_OPP,
SEASON AS YEARS
FROM BASKETBALL_TEST.GAME
WHERE 
TEAM_ID_HOME IN (SELECT DISTINCT ID FROM BASKETBALL.TEAM)
AND
TEAM_ID_AWAY IN (SELECT DISTINCT ID FROM BASKETBALL.TEAM)
AND
LAST_GAME_VISITOR_TEAM_CITY1 IN (SELECT ABBREVIATION FROM BASKETBALL.TEAM);

INSERT INTO BASKETBALL.GAME_INACTIVE_PLAYERS
(
PLAYER_ID,
JERSEY_NUM,
TEAM_ID,
GAME_ID
)
SELECT
PLAYER_ID,
JERSEY_NUM,
TEAM_ID,
GAME_ID
FROM BASKETBALL_TEST.GAME_INACTIVE_PLAYERS;

INSERT INTO BASKETBALL.GAME_OFFICIAL_ATTRIBUTES
(
OFFICIAL_ID,
FIRST_NAME,
LAST_NAME,
JERSEY_NUM,
GAME_ID
)
SELECT
OFFICIAL_ID,
FIRST_NAME,
LAST_NAME,
JERSEY_NUM,
GAME_ID
FROM BASKETBALL_TEST.GAME_OFFICIALS;

insert into basketball.player_attributes
 (ID,
FULL_NAME,
PLAYER_SLUG,
BIRTHDATE,
SCHOOL,
COUNTRY ,
LAST_AFFILIATION,
HEIGHT,
WEIGHT,
SEASON_EXP,
JERSEY,
POSITION,
ROSTERSTATUS,
GAMES_PLAYED_CURRENT_SEASON_FLAG,
TEAM_ID,
PLAYERCODE,
FROM_YEAR,
TO_YEAR,
DLEAGUE_FLAG,
NBA_FLAG,
GAMES_PLAYED_FLAG,
PTS,
AST,
REB,
ALL_STAR_APPEARANCES,
PIE)
select distinct ID,concat(first_name,' ',last_name) full_name
,PLAYER_SLUG
,substr(BIRTHDATE,1,10) as BIRTHDATE
,SCHOOL
,COUNTRY
,LAST_AFFILIATION
,HEIGHT
,WEIGHT
,SEASON_EXP
,case when trim(JERSEY) = '' then null else JERSEY end as JERSEY
,POSITION
,ROSTERSTATUS
,GAMES_PLAYED_CURRENT_SEASON_FLAG
,TEAM_ID
,PLAYERCODE
,FROM_YEAR
,TO_YEAR
,DLEAGUE_FLAG
,NBA_FLAG
,GAMES_PLAYED_FLAG
,PTS
,AST
,REB
,ALL_STAR_APPEARANCES
,PIE
from basketball_test.Player_Attributes
WHERE TEAM_ID IN (SELECT DISTINCT ID FROM BASKETBALL.TEAM)
and ID IN (select ID from BASKETBALL_TEST.player);

insert into basketball.player_salary
(
SLUGSEASON,
NAMETEAM,
NAMEPLAYER,
STATUSPLAYER,
ISFINALSEASON,
ISWAIVED,
ISONROSTER,
ISNONGUARANTEED,
ISTEAMOPTION,
ISPLAYEROPTION,
TYPECONTRACTDETAIL,
SALARY)
select
SLUGSEASON,
NAMETEAM,
NAMEPLAYER,
STATUSPLAYER,
ISFINALSEASON,
ISWAIVED,
ISONROSTER,
ISNONGUARANTEED,
ISTEAMOPTION,
ISPLAYEROPTION,
TYPECONTRACTDETAIL,
`value`
from basketball_test.player_salary
where NAMETEAM IN (select FULL_NAME from BASKETBALL.team)
and NAMEPLAYER IN (select FULL_NAME from BASKETBALL.PLAYER_ATTRIBUTES);

insert into basketball.team_attributes
(ID, 
ABBREVIATION, 
YEARFOUNDED, 
ARENA, 
ARENACAPACITY ,
OWNERName, 
GENERALMANAGER, 
HEADCOACH, 
DLEAGUEAFFILIATION, 
FACEBOOK_WEBSITE_LINK, 
INSTAGRAM_WEBSITE_LINK, 
TWITTER_WEBSITE_LINK)
select
ID, 
ABBREVIATION, 
YEARFOUNDED, 
ARENA, 
ARENACAPACITY ,
`OWNER`, 
GENERALMANAGER, 
HEADCOACH, 
DLEAGUEAFFILIATION, 
FACEBOOK_WEBSITE_LINK, 
INSTAGRAM_WEBSITE_LINK, 
TWITTER_WEBSITE_LINK
from basketball_test.team_attributes
WHERE ID IN (SELECT DISTINCT ID FROM BASKETBALL.TEAM);

INSERT INTO BASKETBALL.TEAM_HISTORY(
TEAM_ID
,CITY
,NICKNAME
,YEARFOUNDED
,YEARACTIVETILL
)
SELECT 
distinct ID
,CITY
,NICKNAME
,YEARFOUNDED
,YEARACTIVETILL
FROM BASKETBALL_TEST.TEAM_HISTORY
WHERE ID IN (SELECT DISTINCT ID FROM BASKETBALL.TEAM);

INSERT INTO BASKETBALL.TEAM_SALARY(
NAMETEAM
,SLUGTEAM
,URLTEAMSALARYHOOPSHYPE
,X2020_21
,X2021_22
,X2022_23
,X2023_24
,X2024_25
,X2025_26)
SELECT
NAMETEAM
,SLUGTEAM
,URLTEAMSALARYHOOPSHYPE
,`X2020-21`
,`X2021-22`
,`X2022-23`
,`X2023-24`
,`X2024-25`
,`X2025-26`
FROM BASKETBALL_TEST.TEAM_SALARY
where NAMETEAM IN (select FULL_NAME from BASKETBALL.team);

insert into BASKETBALL.game_officials (
GAME_GAME_ID
,GAME_OFFICIALS_OFFICIAL_ID
)
SELECT
t1.game_id
,official_id
from BASKETBALL.game t1
join BASKETBALL.game_official_attributes t2 using (game_id);