CREATE OR REPLACE VIEW GAME_ANALYSIS AS
WITH 
CTE_TEAM_LOCATION_GAME_STATS AS
(
	SELECT
		TEAM_ID_HOME AS TEAM_ID
		,SEASON_ID AS SEASON
		,'HOME' AS LOCATION
		,SUM(CASE WHEN WL_HOME = 'W' THEN 1 ELSE 0 END) AS WIN_COUNT
		-- GOAL EFFICIENCY
		,ROUND(AVG(FG_PCT_HOME),2) AS `AVERAGE_2_POINT_GOAL_EFFICIENCY`
		,ROUND(AVG(FG3_PCT_HOME),2) AS `AVERAGE_3_POINT_GOAL_EFFICIENCY`
		,ROUND(AVG(FGM_HOME/PTS_HOME),2) AS `AVERAGE_2_POINT_GOAL_PERCENTAGE`
		,ROUND(AVG(FG3M_HOME/PTS_HOME),2) AS `AVERAGE_3_POINT_GOAL_PERCENTAGE`
		,ROUND(SUM(FTM_HOME)/SUM(FTA_HOME),2) AS `FREE_THROUGH_GOAL_EFFICIENCY`
        ,ROUND(SUM(FTM_HOME)/SUM(PTS_HOME),2) AS `FREE_THROUGH_GOAL_PERCENTAGE`
		-- OFFENSE STRATEGY COLUMNS
		,ROUND(AVG(OREB_HOME/REB_HOME),2) AS `OFFENSIVE_REBOUND_PERCENTAGE`
		,ROUND(AVG(AST_HOME),2) AS `AVERAGE_ASSISTS`
		,ROUND(AVG(PTS_PAINT_HOME/PTS_HOME),2) AS `AVERAGE_PAINT_POINTS`
		,ROUND(AVG(PTS_2ND_CHANCE_HOME/PTS_HOME),2) AS `AVERAGE_2ND_CHANCE_POINTS`
		-- DEFENSE STRATEGY COLUMNS
		,ROUND(AVG(DREB_HOME/REB_HOME),2) AS `DEFENSIVE_REBOUND_PERCENTAGE` 
		,ROUND(AVG(STL_HOME),2) AS `AVERAGE_NUMBER_OF_STEALS`
		,ROUND(AVG(BLK_HOME),2) AS `AVERAGE_NUMBER_OF_BLOCKS`
		,ROUND(AVG(PTS_OFF_TO_HOME/PTS_HOME),2) AS `AVERAGE_POINTS_AFTER_TURNOVER_PERCENTAGE`
		-- FOUL COLUMNS
		,ROUND(AVG(PF_HOME),2) AS `AVERGAE_FOULS`
		,ROUND(AVG(TOV_HOME),2) AS `AVERAGE_TURNOVER`
		,COUNT(GAME_ID) AS GAME_COUNT
	FROM 
		GAME
	-- WHERE SEASON_ID >= 2000
	GROUP BY 1,2,3

	UNION

	SELECT	
		TEAM_ID_OPP AS TEAM_ID
		,SEASON_ID AS SEASON	
		,'AWAY' AS LOCATION	
		,SUM(CASE WHEN WL_OPP = 'W' THEN 1 ELSE 0 END) AS WIN_COUNT
		-- GOAL EFFICIENCY	
		,ROUND(AVG(FG_PCT_OPP),2) AS `AVERAGE_2_POINT_GOAL_EFFICIENCY`	
		,ROUND(AVG(FG3_PCT_OPP),2) AS `AVERAGE_3_POINT_GOAL_EFFICIENCY`	
		,ROUND(AVG(FGM_OPP/PTS_OPP),2) AS `AVERAGE_2_POINT_GOAL_PERCENTAGE`	
		,ROUND(AVG(FG3M_OPP/PTS_OPP),2) AS `AVERAGE_3_POINT_GOAL_PERCENTAGE`	
		,ROUND(SUM(FTM_OPP)/SUM(FTA_OPP),2) AS `FREE_THROUGH_GOAL_EFFICIENCY`	
        ,ROUND(SUM(FTM_OPP)/SUM(PTS_OPP),2) AS `FREE_THROUGH_GOAL_PERCENTAGE`
		-- OFFENSE STRATEGY COLUMNS	
		,ROUND(AVG(OREB_OPP/REB_OPP),2) AS `OFFENSIVE_REBOUND_PERCENTAGE`	
		,ROUND(AVG(AST_OPP),2) AS `AVERAGE_ASSISTS`	
		,ROUND(AVG(PTS_PAINT_OPP/PTS_OPP),2) AS `AVERAGE_PAINT_POINTS`	
		,ROUND(AVG(PTS_2ND_CHANCE_OPP/PTS_OPP),2) AS `AVERAGE_2ND_CHANCE_POINTS`	
		-- DEFENSE STRATEGY COLUMNS	
		,ROUND(AVG(DREB_OPP/REB_OPP),2) AS `DEFENSIVE_REBOUND_PERCENTAGE` 	
		,ROUND(AVG(STL_OPP),2) AS `AVERAGE_NUMBER_OF_STEALS`	
		,ROUND(AVG(BLK_OPP),2) AS `AVERAGE_NUMBER_OF_BLOCKS`	
		,ROUND(AVG(PTS_OFF_TO_OPP/PTS_OPP),2) AS `AVERAGE_POINTS_AFTER_TURNOVER_PERCENTAGE`	
		-- FOUL COLUMNS	
		,ROUND(AVG(PF_OPP),2) AS `AVERGAE_FOULS`	
		,ROUND(AVG(TOV_OPP),2) AS `AVERAGE_TURNOVER`	
		,COUNT(GAME_ID) AS GAME_COUNT	
	FROM 	
		GAME
	-- WHERE SEASON_ID >= 2000	
	GROUP BY 1,2,3

	ORDER BY 1,2 DESC,3
),

CTE_TEAM_GAME_STATS AS
(
SELECT 
	*
    ,SUM(`WIN_COUNT`) OVER (PARTITION BY TEAM_ID, SEASON) AS `TOTAL_WIN_COUNT`
	,ROUND(AVG(`AVERAGE_2_POINT_GOAL_EFFICIENCY`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_2_POINT_GOAL_EFFICIENCY`
	,ROUND(AVG(`AVERAGE_3_POINT_GOAL_EFFICIENCY`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_3_POINT_GOAL_EFFICIENCY`
	,ROUND(AVG(`AVERAGE_2_POINT_GOAL_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_2_POINT_GOAL_PERCENTAGE`
	,ROUND(AVG(`AVERAGE_3_POINT_GOAL_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_3_POINT_GOAL_PERCENTAGE`
	,ROUND(AVG(`FREE_THROUGH_GOAL_EFFICIENCY`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_FREE_THROUGH_GOAL_EFFICIENCY`
    ,ROUND(AVG(`FREE_THROUGH_GOAL_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_FREE_THROUGH_GOAL_PERCENTAGE`
	,ROUND(AVG(`OFFENSIVE_REBOUND_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_OFFENSIVE_REBOUND_PERCENTAGE`
	,ROUND(AVG(`AVERAGE_ASSISTS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_ASSISTS`
	,ROUND(AVG(`AVERAGE_PAINT_POINTS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_PAINT_POINTS`
	,ROUND(AVG(`AVERAGE_2ND_CHANCE_POINTS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_2ND_CHANCE_POINTS`
	,ROUND(AVG(`DEFENSIVE_REBOUND_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_DEFENSIVE_REBOUND_PERCENTAGE`
	,ROUND(AVG(`AVERAGE_NUMBER_OF_STEALS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_NUMBER_OF_STEALS`
	,ROUND(AVG(`AVERAGE_NUMBER_OF_BLOCKS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_NUMBER_OF_BLOCKS`
	,ROUND(AVG(`AVERAGE_POINTS_AFTER_TURNOVER_PERCENTAGE`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_POINTS_AFTER_TURNOVER_PERCENTAGE`
	,ROUND(AVG(`AVERGAE_FOULS`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERGAE_FOULS`
	,ROUND(AVG(`AVERAGE_TURNOVER`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_AVERAGE_TURNOVER`
	,ROUND(SUM(`GAME_COUNT`) OVER (PARTITION BY TEAM_ID, SEASON),2) AS `TOTAL_GAME_COUNT`
FROM 
	CTE_TEAM_LOCATION_GAME_STATS
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
ORDER BY 1,2 DESC, 3
)
SELECT 
	CTE.* 
    ,T.FULL_NAME AS TEAM_NAME
    ,T.ABBREVIATION AS TEAM_SLUG
FROM 
	CTE_TEAM_GAME_STATS CTE
    INNER JOIN
    TEAM T
    ON CTE.TEAM_ID = T.ID;

SELECT * FROM GAME_ANALYSIS;