CREATE OR REPLACE VIEW PLAYER_STATS_WITH_SALARY AS
WITH 
CTE_PLAYER AS
(
	SELECT *
	FROM  
		(
        SELECT 
			ID AS PLAYER_ID
			,FULL_NAME AS PLAYER_NAME
			,SCHOOL
			,COUNTRY
			,BIRTHDATE
			,TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE()) AS PLAYER_CURRENT_AGE
			,HEIGHT
			,WEIGHT
			,SEASON_EXP
			,`POSITION`
			,ROSTERSTATUS
			,TEAM_ID
			,PTS
			,REB
			,AST
        FROM
			PLAYER_ATTRIBUTES 
        ) AS PA
        INNER JOIN
        (
        SELECT
			NAMEPLAYER AS PLAYER_NM
            ,MAX(CASE WHEN SLUGSEASON = '2020-21' THEN TYPECONTRACTDETAIL END) AS `2020 - 2021 CONTRACT TYPE`
            ,SUM(CASE WHEN SLUGSEASON = '2020-21' THEN SALARY END) AS `2020 - 2021 SALARY`
            ,MAX(CASE WHEN SLUGSEASON = '2021-22' THEN TYPECONTRACTDETAIL END) AS `2021 - 2022 CONTRACT TYPE`
            ,SUM(CASE WHEN SLUGSEASON = '2021-22' THEN SALARY END) AS `2021 - 2022 SALARY`
            ,MAX(CASE WHEN SLUGSEASON = '2022-23' THEN TYPECONTRACTDETAIL END) AS `2022 - 2023 CONTRACT TYPE`
            ,SUM(CASE WHEN SLUGSEASON = '2022-23' THEN SALARY END) AS `2022 - 2023 SALARY`
            ,MAX(CASE WHEN SLUGSEASON = '2023-24' THEN TYPECONTRACTDETAIL END) AS `2023 - 2024 CONTRACT TYPE`
            ,SUM(CASE WHEN SLUGSEASON = '2023-24' THEN SALARY END) AS `2023 - 2024 SALARY`
        FROM
			PLAYER_SALARY 
		GROUP BY 1
        ORDER BY 1
        ) AS PS
        ON PA.PLAYER_NAME = PS.PLAYER_NM
)
SELECT * FROM CTE_PLAYER;