CREATE OR REPLACE VIEW TEAM_WINNING_STATS_WITH_SALARY AS
WITH 
CTE_HOME_OPP_WINS_LOSSES AS
(
	SELECT 
		TEAM_ID_HOME
		,TEAM_ID_OPP
		,WL_HOME
		,WL_OPP
		,COUNT(CASE WHEN WL_HOME = 'W' THEN GAME_ID ELSE NULL END) AS HOME_TEAM_WINS
		,COUNT(CASE WHEN WL_HOME = 'L' THEN GAME_ID ELSE NULL END) AS OPP_TEAM_WINS
	FROM  
		GAME G
	GROUP BY 1,2,3,4
),
CTE_HOME_AWAY_WIN_LOSS_COUNT AS
(
	SELECT
		CASE WHEN WL_HOME = 'W' THEN TEAM_ID_HOME WHEN WL_HOME = 'L' THEN TEAM_ID_OPP END AS TEAM_ID
		,CASE WHEN WL_HOME = 'W' THEN 'HOME' WHEN WL_HOME = 'L' THEN 'AWAY' END AS LOCATION
		, 'WIN' AS MATCH_STATUS
		,SUM(CASE WHEN WL_HOME = 'W' THEN HOME_TEAM_WINS WHEN WL_HOME = 'L' THEN OPP_TEAM_WINS END) AS GAME_COUNT
	FROM
		CTE_HOME_OPP_WINS_LOSSES
	GROUP BY 1,2,3
	UNION
	SELECT
		CASE WHEN WL_HOME = 'L' THEN TEAM_ID_HOME WHEN WL_HOME = 'W' THEN TEAM_ID_OPP END AS TEAM_ID
		,CASE WHEN WL_HOME = 'W' THEN 'AWAY' WHEN WL_HOME = 'L' THEN 'HOME' END AS LOCATION
		,'LOST' AS MATCH_STATUS
		,SUM(CASE WHEN WL_HOME = 'W' THEN HOME_TEAM_WINS WHEN WL_HOME = 'L' THEN OPP_TEAM_WINS END) AS GAME_COUNT
	FROM
		CTE_HOME_OPP_WINS_LOSSES
	GROUP BY 1,2,3
	ORDER BY 1,3,2
),
CTE_HOME_AWAY_WIN_LOSS_GAME_COUNT AS
(
	SELECT 
		TEAM_ID
		,LOCATION
		,MATCH_STATUS
		,GAME_COUNT
		,SUM(GAME_COUNT) OVER (PARTITION BY TEAM_ID, LOCATION) AS TOTAL_GAMES_AT_LOCATION
		,SUM(GAME_COUNT) OVER (PARTITION BY TEAM_ID) AS TOTAL_GAMES
	FROM
		CTE_HOME_AWAY_WIN_LOSS_COUNT
	GROUP BY 1,2,3,4
)
SELECT 
	TEAM_ID
    ,FULL_NAME AS TEAM_NAME
    ,CITY AS TEAM_CITY
    ,ABBREVIATION AS TEAM_SLUG
    ,YEAR_FOUNDED
    ,X2020_21 AS `2020-2021 SALARY`
    ,X2021_22 AS `2021-2022 SALARY`
    ,X2022_23 AS `2022-2023 SALARY`
    ,X2023_24 AS `2023-2024 SALARY`
    ,X2024_25 AS `2024-2025 SALARY`
    ,X2025_26 AS `2025-2026 SALARY`
	,SUM(ROUND(CASE WHEN LOCATION = "HOME" AND MATCH_STATUS = "WIN" THEN GAME_COUNT/TOTAL_GAMES_AT_LOCATION END, 2)) AS `HOME WIN %`
	,SUM(ROUND(CASE WHEN LOCATION = "HOME" AND MATCH_STATUS = "LOST" THEN GAME_COUNT/TOTAL_GAMES_AT_LOCATION END, 2)) AS `HOME LOSS %`
	,SUM(ROUND(CASE WHEN LOCATION = "AWAY" AND MATCH_STATUS = "WIN" THEN GAME_COUNT/TOTAL_GAMES_AT_LOCATION END, 2)) AS `AWAY WIN %`
	,SUM(ROUND(CASE WHEN LOCATION = "AWAY" AND MATCH_STATUS = "LOST" THEN GAME_COUNT/TOTAL_GAMES_AT_LOCATION END, 2)) AS `AWAY LOSS %`
	,SUM(ROUND(CASE WHEN MATCH_STATUS = "WIN" THEN GAME_COUNT/TOTAL_GAMES END, 2)) AS `TOTAL WIN %`
	,SUM(ROUND(CASE WHEN MATCH_STATUS = "LOST" THEN GAME_COUNT/TOTAL_GAMES END, 2)) AS `TOTAL LOSS %`
FROM 
	CTE_HOME_AWAY_WIN_LOSS_GAME_COUNT CTE
    INNER JOIN
    TEAM T
    ON CTE.TEAM_ID = T.ID
    INNER JOIN
    TEAM_SALARY TS
    ON UPPER(T.ABBREVIATION) = UPPER(TS.SLUGTEAM)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11;
SELECT * FROM TEAM_WINNING_STATS_WITH_SALARY;
-- QC
SELECT TEAM_ID_HOME, WL_HOME, "HOME WINS", COUNT(*) FROM GAME WHERE TEAM_ID_HOME = 1610612737 AND WL_HOME = 'W' GROUP BY 1,2
UNION
SELECT TEAM_ID_HOME, WL_HOME, "HOME LOSSES", COUNT(*) FROM GAME WHERE TEAM_ID_HOME = 1610612737 AND WL_HOME = 'L' GROUP BY 1,2
UNION
SELECT TEAM_ID_OPP, WL_HOME, "AWAY LOSSES", COUNT(*) FROM GAME WHERE TEAM_ID_OPP = 1610612737 AND WL_HOME = 'W' GROUP BY 1,2
UNION
SELECT TEAM_ID_OPP, WL_HOME, "AWAY WINS", COUNT(*) FROM GAME WHERE TEAM_ID_OPP = 1610612737 AND WL_HOME = 'L' GROUP BY 1,2;